#!/bin/sh
# A script that echos a string representation of all the current notifications
# as a FIFO queue.
# ex: "[first][second][third].."
notifyString=""
for notify in ~/.notifications/* ; do
    [ -f "$notify" ] || continue
    notifyString="[$(cat $notify)]$notifyString"
done
echo "$notifyString"
